name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALPHA_ORACLE_SSH_HOST }}
          username: ${{ secrets.ALPHA_ORACLE_SSH_USERNAME }}
          key: ${{ secrets.ALPHA_ORACLE_SSH_KEY }}
          port: ${{ secrets.ALPHA_ORACLE_SSH_PORT }}
          script: |
            whoami

            # Set NODE_ENV on the server
            echo "export NODE_ENV=${{ secrets.ALPHA_ORACLE_SSH_ENV }}" >> ~/.bashrc
            source ~/.bashrc

            cd ~/backtodiary
            sudo git pull origin main

            # Copy server-specific config
            cp /path/to/your/config/* ~/backtodiary/config/

            yarn install
            pm2 restart app