name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALPHA_ORACLE_SSH_HOST }}
          username: ${{ secrets.ALPHA_ORACLE_SSH_USERNAME }}
          key: ${{ secrets.ALPHA_ORACLE_SSH_KEY }}
          port: ${{ secrets.ALPHA_ORACLE_SSH_PORT }}
          script: |
            whoami
            cd ~/backtodiary
            sudo git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            yarn install
            pm2 restart app